export const USER_CONNEXION_REQUEST = 'USER_CONNEXION_REQUEST';
export const USER_CONNEXION_SUCCESS = 'USER_CONNEXION_SUCCESS';
export const USER_CONNEXION_FAIL = 'USER_CONNEXION_FAIL';


export const USER_DECONNEXION = 'USER_DECONNEXIONT';



export const USER_INSCRIPTION_REQUEST = 'USER_INSCRIPTION_REQUEST';
export const USER_INSCRIPTION_SUCCESS = 'USER_INSCRIPTION_SUCCESS';
export const USER_INSCRIPTION_FAIL = 'USER_INSCRIPTION_FAIL';



export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';



export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';